version: "3.9"

services:
  db:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_DB=linksnest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5454:5432"
    volumes:
      - linksnestdb:/var/lib/postgresql/data/
  backend:
    build:
      context: backend
    command: "yarn start:dev"
    volumes:
#      - ./backend:/backend
      - ./backend/src:/backend/src
      - ./backend/package.json:/backend/package.json
      - ./backend/package-lock.json:/backend/package-lock.json
    ports:
      - "4000:4000"
    depends_on:
      - db
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src
volumes:
    linksnestdb: