version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=linksnest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5454:5432"
    volumes:
      - linksnestdb:/backend/db
#  migrations:
#    build: migrations
#    command: "yarn run migrate"
#    depends_on:
#      - db
##    volumes:
##      - ./backend/src:/backend/src

  backend:
    build:
      context: backend
    command: "yarn start:dev"
#    volumes:
#      - ./backend:/backend
    ports:
      - "4000:4000"
    depends_on:
      - db
#      - migrations
volumes:
    linksnestdb: